openapi: 3.0.0
info:
  title: TB pemograman
  version: 1.0.0
servers:
  - url: https://server-pemograman.vercel.app
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /register:
    post:
      tags:
        - default
      summary: Register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                full_name: John Doe
                nickname: johnny
                email: johnTes@example.com
                phone_number: '1234567890'
                password: yourpassword
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /login:
    post:
      tags:
        - default
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                usernameEmail: john@example.com
                password: yourpassword
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /item:
    post:
      tags:
        - default
      summary: Create Item
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: tes
                description: tes
                price: 12
                quantity: 50
                category: 1
      security:
        - bearerAuth: []
      parameters:
        - name: LOGIN
          in: header
          schema:
            type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxLCJpZF9yb2xlIjoyLCJleHAiOjE3MTkxMzA3MDksImlzcyI6Im15YXBwIn0.Kjh2aiPkIvY5qznuintIYKajRopd6WH7sgM66xRGbLo
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /items:
    get:
      tags:
        - default
      summary: Get item
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /items/1:
    get:
      tags:
        - default
      summary: get item by id
      parameters:
        - name: id_item
          in: header
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /delete/item/1:
    delete:
      tags:
        - default
      summary: delete item
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
